const userTypes={

    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS ',

    CHECK_USER_SESSION: 'CHECK_USER_SESSION',

    SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
    SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',

    RESET_PASSWORD_START: 'RESET_PASSWORD_START',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',

    USER_ERROR: 'USER_ERROR',
    SIGN_IN_ERROR:'SIGN_IN_ERROR',
    RESET_USER_STATE: 'RESET_USER_STATE',
    UPDATE_IMAGE_START: 'UPDATE_IMAGE_START',
    UPDATE_TEXT_START: 'UPDATE_TEXT_START',    

    //To BE DONE

    FETCH_USER_START: 'FETCH_USER_START',
    SET_USER: 'SET_USER',
    SET_USER_PERCENTAGE : 'SET_USER_PERCENTAGE',

    FETCH_ALL_USERS_START: 'FETCH_ALL_USERS_START',
    SET_ALL_USERS: 'SET_ALL_USERS',

    
    



};
export default userTypes;