const imagesTypes={

    ADD_NEW_IMAGE_START : 'ADD_IMAGE_START', 
    DELETE_IMAGE_START: 'DELETE_IMAGES_START',
    FETCH_STORY_IMAGES_START: 'FETCH_STORY_IMAGES_START',
    SET_STORY_IMAGES: 'SET_STORY_IMAGES',
    SET_PERCENTAGE: 'SET_PERCENTAGE' ,

  
};
export default imagesTypes;